<?php

use Illuminate\Database\Seeder;

class Menu_itemsTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     *
     * @throws Exception
     */
    public function run()
    {
     try {
        \DB::beginTransaction();

        \DB::table('menu_items')->delete();

        \DB::table('menu_items')->insert(array (
                0 => 
                array (
                    'id' => 1,
                    'menu_id' => 1,
                    'title' => 'Панель управления',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-boat',
                    'color' => '#000000',
                    'parent_id' => NULL,
                    'order' => 1,
                    'created_at' => '2020-08-23 17:10:45',
                    'updated_at' => '2020-09-13 17:20:48',
                    'route' => 'voyager.dashboard',
                    'parameters' => 'null',
                ),
                1 => 
                array (
                    'id' => 2,
                    'menu_id' => 1,
                    'title' => 'Медиа хранилище',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-images',
                    'color' => '#000000',
                    'parent_id' => NULL,
                    'order' => 9,
                    'created_at' => '2020-08-23 17:10:45',
                    'updated_at' => '2020-11-04 00:19:07',
                    'route' => 'voyager.media.index',
                    'parameters' => 'null',
                ),
                2 => 
                array (
                    'id' => 3,
                    'menu_id' => 1,
                    'title' => 'Пользователи',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-person',
                    'color' => '#000000',
                    'parent_id' => NULL,
                    'order' => 11,
                    'created_at' => '2020-08-23 17:10:45',
                    'updated_at' => '2020-11-04 00:19:07',
                    'route' => 'voyager.users.index',
                    'parameters' => 'null',
                ),
                3 => 
                array (
                    'id' => 4,
                    'menu_id' => 1,
                    'title' => 'Роли',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-lock',
                    'color' => '#000000',
                    'parent_id' => NULL,
                    'order' => 10,
                    'created_at' => '2020-08-23 17:10:45',
                    'updated_at' => '2020-11-04 00:19:07',
                    'route' => 'voyager.roles.index',
                    'parameters' => 'null',
                ),
                4 => 
                array (
                    'id' => 5,
                    'menu_id' => 1,
                    'title' => 'Инструменты',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-tools',
                    'color' => '#000000',
                    'parent_id' => NULL,
                    'order' => 14,
                    'created_at' => '2020-08-23 17:10:46',
                    'updated_at' => '2020-11-04 00:19:07',
                    'route' => NULL,
                    'parameters' => '',
                ),
                5 => 
                array (
                    'id' => 6,
                    'menu_id' => 1,
                    'title' => 'Menu Builder',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-list',
                    'color' => NULL,
                    'parent_id' => 5,
                    'order' => 1,
                    'created_at' => '2020-08-23 17:10:46',
                    'updated_at' => '2020-08-31 18:43:14',
                    'route' => 'voyager.menus.index',
                    'parameters' => NULL,
                ),
                6 => 
                array (
                    'id' => 7,
                    'menu_id' => 1,
                    'title' => 'Database',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-data',
                    'color' => NULL,
                    'parent_id' => 5,
                    'order' => 2,
                    'created_at' => '2020-08-23 17:10:46',
                    'updated_at' => '2020-08-31 18:43:14',
                    'route' => 'voyager.database.index',
                    'parameters' => NULL,
                ),
                7 => 
                array (
                    'id' => 8,
                    'menu_id' => 1,
                    'title' => 'Compass',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-compass',
                    'color' => NULL,
                    'parent_id' => 5,
                    'order' => 3,
                    'created_at' => '2020-08-23 17:10:46',
                    'updated_at' => '2020-08-31 18:49:29',
                    'route' => 'voyager.compass.index',
                    'parameters' => NULL,
                ),
                8 => 
                array (
                    'id' => 9,
                    'menu_id' => 1,
                    'title' => 'BREAD',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-bread',
                    'color' => NULL,
                    'parent_id' => 5,
                    'order' => 4,
                    'created_at' => '2020-08-23 17:10:46',
                    'updated_at' => '2020-08-31 18:49:29',
                    'route' => 'voyager.bread.index',
                    'parameters' => NULL,
                ),
                9 => 
                array (
                    'id' => 10,
                    'menu_id' => 1,
                    'title' => 'Настройки',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-settings',
                    'color' => '#000000',
                    'parent_id' => NULL,
                    'order' => 15,
                    'created_at' => '2020-08-23 17:10:46',
                    'updated_at' => '2020-11-04 00:19:07',
                    'route' => 'voyager.settings.index',
                    'parameters' => 'null',
                ),
                10 => 
                array (
                    'id' => 11,
                    'menu_id' => 1,
                    'title' => 'Categories',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-categories',
                    'color' => NULL,
                    'parent_id' => NULL,
                    'order' => 13,
                    'created_at' => '2020-08-23 17:10:59',
                    'updated_at' => '2020-11-04 00:19:07',
                    'route' => 'voyager.categories.index',
                    'parameters' => NULL,
                ),
                11 => 
                array (
                    'id' => 12,
                    'menu_id' => 1,
                    'title' => 'Статьи',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-news',
                    'color' => '#000000',
                    'parent_id' => 30,
                    'order' => 1,
                    'created_at' => '2020-08-23 17:11:01',
                    'updated_at' => '2020-09-04 06:31:44',
                    'route' => 'voyager.posts.index',
                    'parameters' => 'null',
                ),
                12 => 
                array (
                    'id' => 13,
                    'menu_id' => 1,
                    'title' => 'Pages',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-file-text',
                    'color' => NULL,
                    'parent_id' => NULL,
                    'order' => 12,
                    'created_at' => '2020-08-23 17:11:02',
                    'updated_at' => '2020-11-04 00:19:07',
                    'route' => 'voyager.pages.index',
                    'parameters' => NULL,
                ),
                13 => 
                array (
                    'id' => 14,
                    'menu_id' => 1,
                    'title' => 'Hooks',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-hook',
                    'color' => NULL,
                    'parent_id' => 5,
                    'order' => 5,
                    'created_at' => '2020-08-23 17:11:05',
                    'updated_at' => '2020-08-31 18:49:29',
                    'route' => 'voyager.hooks',
                    'parameters' => NULL,
                ),
                14 => 
                array (
                    'id' => 15,
                    'menu_id' => 1,
                    'title' => 'Продукты',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-basket',
                    'color' => '#000000',
                    'parent_id' => 29,
                    'order' => 1,
                    'created_at' => '2020-08-24 05:30:53',
                    'updated_at' => '2020-09-04 06:20:42',
                    'route' => 'voyager.products.index',
                    'parameters' => 'null',
                ),
                15 => 
                array (
                    'id' => 16,
                    'menu_id' => 1,
                    'title' => 'Группа Категории',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-archive',
                    'color' => '#000000',
                    'parent_id' => 29,
                    'order' => 2,
                    'created_at' => '2020-08-24 05:41:26',
                    'updated_at' => '2020-09-04 06:22:00',
                    'route' => 'voyager.category.index',
                    'parameters' => 'null',
                ),
                16 => 
                array (
                    'id' => 17,
                    'menu_id' => 1,
                    'title' => 'Элементы категории',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-list',
                    'color' => '#000000',
                    'parent_id' => 29,
                    'order' => 3,
                    'created_at' => '2020-08-24 05:47:16',
                    'updated_at' => '2020-09-11 08:36:22',
                    'route' => 'voyager.category-items.index',
                    'parameters' => 'null',
                ),
                17 => 
                array (
                    'id' => 18,
                    'menu_id' => 1,
                    'title' => 'Тип фасовка продукты',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-rum-1',
                    'color' => '#000000',
                    'parent_id' => 29,
                    'order' => 4,
                    'created_at' => '2020-08-24 18:36:34',
                    'updated_at' => '2020-09-11 08:36:22',
                    'route' => 'voyager.product-type-packings.index',
                    'parameters' => 'null',
                ),
                18 => 
                array (
                    'id' => 19,
                    'menu_id' => 1,
                    'title' => 'Контентные страницы',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-info-circled',
                    'color' => '#000000',
                    'parent_id' => 30,
                    'order' => 3,
                    'created_at' => '2020-08-26 11:37:11',
                    'updated_at' => '2020-11-04 02:00:08',
                    'route' => 'voyager.content-menus.index',
                    'parameters' => 'null',
                ),
                19 => 
                array (
                    'id' => 20,
                    'menu_id' => 1,
                    'title' => 'Химикаты',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-lab',
                    'color' => '#000000',
                    'parent_id' => 30,
                    'order' => 4,
                    'created_at' => '2020-08-30 05:22:29',
                    'updated_at' => '2020-10-02 08:00:38',
                    'route' => 'voyager.chemicals.index',
                    'parameters' => 'null',
                ),
                20 => 
                array (
                    'id' => 22,
                    'menu_id' => 1,
                    'title' => 'Заявки',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-thumb-tack',
                    'color' => '#000000',
                    'parent_id' => NULL,
                    'order' => 6,
                    'created_at' => '2020-08-30 05:40:03',
                    'updated_at' => '2020-11-04 00:19:07',
                    'route' => 'voyager.propositions.index',
                    'parameters' => 'null',
                ),
                21 => 
                array (
                    'id' => 24,
                    'menu_id' => 1,
                    'title' => 'Действующее вещество',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-campfire',
                    'color' => '#000000',
                    'parent_id' => 30,
                    'order' => 5,
                    'created_at' => '2020-08-31 08:08:51',
                    'updated_at' => '2020-11-05 06:27:04',
                    'route' => 'voyager.active-substance.index',
                    'parameters' => 'null',
                ),
                22 => 
                array (
                    'id' => 25,
                    'menu_id' => 1,
                    'title' => 'Документы',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-documentation',
                    'color' => '#000000',
                    'parent_id' => NULL,
                    'order' => 7,
                    'created_at' => '2020-08-31 09:38:14',
                    'updated_at' => '2020-11-04 00:19:07',
                    'route' => 'voyager.documents.index',
                    'parameters' => 'null',
                ),
                23 => 
                array (
                    'id' => 27,
                    'menu_id' => 1,
                    'title' => 'Чаты',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-chat',
                    'color' => '#000000',
                    'parent_id' => NULL,
                    'order' => 5,
                    'created_at' => '2020-08-31 15:05:14',
                    'updated_at' => '2020-11-04 00:19:07',
                    'route' => 'voyager.chat-room.index',
                    'parameters' => 'null',
                ),
                24 => 
                array (
                    'id' => 28,
                    'menu_id' => 1,
                    'title' => 'Заказы',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-truck',
                    'color' => '#000000',
                    'parent_id' => 40,
                    'order' => 1,
                    'created_at' => '2020-08-31 18:23:46',
                    'updated_at' => '2020-11-04 00:19:07',
                    'route' => 'voyager.orders.index',
                    'parameters' => 'null',
                ),
                25 => 
                array (
                    'id' => 29,
                    'menu_id' => 1,
                    'title' => 'Продукт',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-bag',
                    'color' => '#000000',
                    'parent_id' => NULL,
                    'order' => 3,
                    'created_at' => '2020-08-31 18:43:05',
                    'updated_at' => '2020-11-04 00:19:07',
                    'route' => NULL,
                    'parameters' => '',
                ),
                26 => 
                array (
                    'id' => 30,
                    'menu_id' => 1,
                    'title' => 'Страницы',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-photo',
                    'color' => '#000000',
                    'parent_id' => NULL,
                    'order' => 4,
                    'created_at' => '2020-08-31 18:46:05',
                    'updated_at' => '2020-11-04 00:19:07',
                    'route' => NULL,
                    'parameters' => '',
                ),
                27 => 
                array (
                    'id' => 31,
                    'menu_id' => 1,
                    'title' => 'Производители',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-company',
                    'color' => '#000000',
                    'parent_id' => 30,
                    'order' => 7,
                    'created_at' => '2020-09-28 19:36:23',
                    'updated_at' => '2020-10-05 09:47:09',
                    'route' => 'voyager.brands.index',
                    'parameters' => 'null',
                ),
                28 => 
                array (
                    'id' => 32,
                    'menu_id' => 1,
                    'title' => 'Лицензии',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-certificate',
                    'color' => '#000000',
                    'parent_id' => NULL,
                    'order' => 8,
                    'created_at' => '2020-09-30 13:59:04',
                    'updated_at' => '2020-11-04 00:19:07',
                    'route' => 'voyager.license.index',
                    'parameters' => 'null',
                ),
                29 => 
                array (
                    'id' => 33,
                    'menu_id' => 1,
                    'title' => 'Нормы применения',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-receipt',
                    'color' => '#000000',
                    'parent_id' => 29,
                    'order' => 5,
                    'created_at' => '2020-09-30 19:23:36',
                    'updated_at' => '2020-10-01 04:37:37',
                    'route' => 'voyager.norms.index',
                    'parameters' => 'null',
                ),
                30 => 
                array (
                    'id' => 35,
                    'menu_id' => 1,
                'title' => 'Справочник(FAQ)',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-bubble',
                    'color' => '#000000',
                    'parent_id' => 30,
                    'order' => 2,
                    'created_at' => '2020-10-02 07:33:08',
                    'updated_at' => '2020-10-02 09:29:24',
                    'route' => 'voyager.faqs.index',
                    'parameters' => 'null',
                ),
                31 => 
                array (
                    'id' => 36,
                    'menu_id' => 1,
                    'title' => 'Культуры',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-tree',
                    'color' => '#000000',
                    'parent_id' => 30,
                    'order' => 6,
                    'created_at' => '2020-10-03 14:17:46',
                    'updated_at' => '2020-10-05 09:51:00',
                    'route' => 'voyager.fruits.index',
                    'parameters' => 'null',
                ),
                32 => 
                array (
                    'id' => 37,
                    'menu_id' => 1,
                    'title' => 'Статусы заказов',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-eye',
                    'color' => '#000000',
                    'parent_id' => 40,
                    'order' => 2,
                    'created_at' => '2020-11-03 21:14:32',
                    'updated_at' => '2020-11-04 00:34:47',
                    'route' => 'voyager.order-status.index',
                    'parameters' => 'null',
                ),
                33 => 
                array (
                    'id' => 38,
                    'menu_id' => 1,
                    'title' => 'Тип оплаты заказы',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-credit-cards',
                    'color' => '#000000',
                    'parent_id' => 40,
                    'order' => 3,
                    'created_at' => '2020-11-04 00:08:55',
                    'updated_at' => '2020-11-04 00:32:12',
                    'route' => 'voyager.order-payment-types.index',
                    'parameters' => 'null',
                ),
                34 => 
                array (
                    'id' => 39,
                    'menu_id' => 1,
                    'title' => 'Тип доставки заказы',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-rocket',
                    'color' => '#000000',
                    'parent_id' => 40,
                    'order' => 4,
                    'created_at' => '2020-11-04 00:11:45',
                    'updated_at' => '2020-11-04 00:35:07',
                    'route' => 'voyager.order-shipping-types.index',
                    'parameters' => 'null',
                ),
                35 => 
                array (
                    'id' => 40,
                    'menu_id' => 1,
                    'title' => 'Заказы',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-truck',
                    'color' => '#000000',
                    'parent_id' => NULL,
                    'order' => 2,
                    'created_at' => '2020-11-04 00:18:45',
                    'updated_at' => '2020-11-04 00:20:14',
                    'route' => NULL,
                    'parameters' => '',
                ),
            ));
       } catch(Exception $e) {
         throw new Exception('Exception occur ' . $e);

         \DB::rollBack();
       }

       \DB::commit();
    }
}
